---
spring:
  profiles: primary
eureka:
  client:
    service-url:
      defaultZone: http://eureka-secondary:8002/eureka/
server:
  port: 8001
---
spring:
  profiles: secondary
eureka:
  client:
    service-url:
      defaultZone: http://eureka-primary:8001/eureka/
server:
  port: 8002